### ISSUE TITLE
some more info

### ISSUE THREAD

**Issue by TRaSH-** [fopina/pokebox#1]
do you have maybe some more info about this container ?
can we check on a web GUI like on the phone app ?
you say we can get a notification how ?

**Comment by fopina** [comment]
Hey I don’t think I finished this because the purpose was to be able to run this in a raspberry and it was too heavy for the Pi (nmap running I mean)
My plan is to convert this to golang, single binary + nmap dependency and provide the container but also be able to run without docker.

But yes, there is a

**Comment by fopina** [comment]
(sorry for double posting but unable to edit previous comment)

But yes, there is a web GUI and it is mentioned in the readme. Also the initial setup required to create the admin user.

Notifications should be working but I never got to test them in my Pi so they were not documented.

**Comment by TRaSH-** [comment]
Thx,
Did see the port stuff etc.
But I didn't read it completely because I wanted to run it on my Ubuntu VM where I run my container's.
